# ----------------------------------------------------------------------- #
#                                                                         #
#                               YMAL文件语法                               #
#                       http://medai.icu/thread/677                       #
#                                                                         #
# ----------------------------------------------------------------------- #
# 你自己的影像数据【目录】，里面需要包括images、masks文件夹
radio_dir: C:\Users\onekey\Desktop\demo\20250328\ddata
# 带有group分组的label文件位置
label_file: C:\Users\onekey\Desktop\tra\split_info\label-RND-0.csv
# 临床数据位置，不要有label和group信息
clinic_file: C:\Users\onekey\Desktop\demo\20250328\clinical.csv
# 你要用什么mask id进行建模。 绝大多数都是1。 
intra_mask_id: 1
# 一般不用动，研究结局的列名，以及用来区分cohort的列名
task_column: label
dataset_column: group
# 衡量显著性的阈值，一般别动！
pvalue: 0.05
# 是否使用分形维数特征，默认是False，当ROI比较小或者是单层(超声数据)的时候会导致计算失败。
with_fd: False
# 是否使用拓扑组学特征，默认是False
with_toplogy: False
# 是否使用hessian矩阵特征，默认是False
with_hessian: False
# 提取传统组学特征的配置文件param_file参数设置，在custom_settings文件夹里面按需选择
extractor_settings: 
# 是否使用SMOTE，解决样本不均衡的问题。
use_smote: False
# 使用MRMR模型筛选特征, 不输入数据的时候，不使用mRMR，默认不使用, 特征多的时候在考虑
mrmr_sel_feature_num: 
# 你打算使用什么机器学习算法建模，先全选然后挑几个好的~，最后保留3-5个。
ml_models: [LR, SVM, RandomForest, ExtraTrees, XGBoost, LightGBM, nb, AdaBoost, GradientBoost]
# 你自己的label文件，group列一共有多少cohorts. | ValueError: Found array with 0 sample(s)(shape=(0, 2))while a minimum of 1 is required
# 只在指标汇总的时候生效。
subsets: [train, val, test]
# 对比不同算法
compare_algos: [Radiomics_LR, Radiomics_SVM, Radiomics_RandomForest, Radiomics_XGBoost]
# 汇总的模型
summary_models: [Clinic, Radiomics, Combined]
# 筛选的模型，注意：不同的Signature可以用不同的机器学习算法。
sel_model: 
  Clinic: ExTraTrees
  Radiomics: ExTraTrees
# 字体大小
font.size: 12
# 是否显示视频
DISABLE_VIDEO: True
PAPER_TMP: Radiomics